language: python
python:
  - "3.3"
install:
  - pip install zc.buildout
  - git clone git://github.com/TangledWeb/tangled ../tangled
  - buildout
script:
  - ls ./bin
  - ./bin/tangled test
  - ./bin/sphinx-build -E docs docs/_build
