language: python
python:
  - "3.3"
  - "3.4"
install:
  - pip install -U setuptools
  - pip install -U pip
  - pip install zc.buildout
  - buildout
  - export PATH=./bin:$PATH
script:
  - tangled test
  - nosetests
  - .sphinx-build -E docs docs/_build
